openapi: 3.0.0
info:
  version: 1.0.0-alpha.1
  title: VAE_HDMapDynamicInfo
  description: |
    API for VAE HDMapDynamicInfo Service
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 29.486 V17.1.0 V2X Application Enabler (VAE) Services
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.486/'
security:
  - {}
  - oAuth2ClientCredentials: []
servers:
  - url: '{apiRoot}/vae-hdmap-dynamic-info/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501
paths:
  /subscriptions:
    post:
      summary: VAE_HDMapDynamicInfo resource create service Operation
      tags:
        - hdmap dynamicinfo subscriptions collection (Document)
      operationId: Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HdMapDynamicInfoData'
        required: true
      responses:
        '201':
          description: HdMap DynamicInfo Subscription Resource Created
          headers:
            Location:
              description: 'Contains the URI of the newly created resource'
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HdMapDynamicInfoData'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
      callbacks:
        NotifyHdMapDynamicInfo:
          '{$request.body#/notifUri}': 
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/HdMapDynamicInfoNotification'
              responses:
                '204':
                  description: No Content, Notification was succesfull
                '307':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/400'
                '401':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29122_CommonData.yaml#/components/responses/default'
  /subscriptions/{subscriptionId}:
    get:
      summary: VAE HdMap DynamicInfo Subscription resource read service Operation
      tags:
        - Individual HdMap DynamicInfo Subscription(Document)
      operationId: ReadHdMapDynamicInfoSubscription
      parameters:
        - name: subscriptionId
          in: path
          description: Identifier of an HdMap DynamicIfo Subscription resource
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. Resource representation is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HdMapDynamicInfoData'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
    delete:
      summary: VAE HdMap DynamicInfo Subscription resource delete service Operation
      tags:
        - Individual hdmap dynamicinfo subscription (Document)
      operationId: DeleteHdMapDynamicInfoSubscription
      parameters:
        - name: subscriptionId
          in: path
          required: true
          description: Unique ID of the hdmap dynamicinfo subscription to be deleted
          schema:
            type: string
      responses:
        '204':
          description: The subscription was terminated successfully.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: '{tokenUrl}'
          scopes: {}
  schemas:
    HdMapDynamicInfoData:
      description: Represents an individual HdMap DynamicInfo Subscription resource for a V2X UE ID.
      type: object
      properties:
        ueId:
          $ref: 'TS29486_VAE_MessageDelivery.yaml#/components/schemas/V2xUeId'
        notifUri:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
        range:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uinteger'
        requestTestNotification:
          type: boolean
          description: Set to true by the NF service consumer to request the VAE server to send a test notification as defined in clause 6.3.5.3. Set to false or omitted otherwise.
        websockNotifConfig:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/WebsockNotifConfig'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - ueId
        - notifUri
        - range
    HdMapDynamicInfoNotification:
      description: Represents a notificaton of HD map dynamic info corresponding to the subscription.
      type: object
      properties:
        resourceUri:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
        nearbyUeInfo:
          type: array
          items:
            $ref: '#/components/schemas/NearbyUeInfo'
          minItems: 1
          description: Contains the informaiotn of nearby UEs.
      required:
        - resourceUri
        - nearbyUeInfo
    NearbyUeInfo:
      description: Represents the informaiotn of nearby UEs.
      type: object
      properties:
        nearbyUeId:
          $ref: 'TS29486_VAE_MessageDelivery.yaml#/components/schemas/V2xUeId'
        location:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/UserLocation'
        distance:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uinteger'
      required:
        - nearbyUeId
        - location
        - distance
