openapi: 3.0.0

info:
  version: '1.1.0-alpha.1'
  title: 'Nhss_UECM'
  description: |
    HSS UE Context Management
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.563 HSS Services for Interworking With UDM, version 17.1.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.563/'

servers:
  - url: '{apiRoot}/nhss-uecm/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

security:
  - oAuth2ClientCredentials:
    - nhss-uecm
  - {}

paths:
  /deregister-sn:
    post:
      summary: MME/SGSN Deregistration
      operationId: DeregisterSN
      tags:
        - MME/SGSN Deregistration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeregistrationRequest'
        required: true
      responses:
        '204':
          description: No content
        '307':
          $ref: 'TS29571_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29571_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '501':
          $ref: 'TS29571_CommonData.yaml#/components/responses/501'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error

  /imei-update:
    post:
      summary: IMEI Update
      operationId: IMEIUpdate
      tags:
        - IMEI Update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImeiUpdateInfo'
        required: true
      responses:
        '204':
          description: No content
        '307':
          $ref: 'TS29571_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29571_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '501':
          $ref: 'TS29571_CommonData.yaml#/components/responses/501'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nhss-uecm: Access to the nhss-uecm API

  schemas:

# COMPLEX TYPES:

    DeregistrationRequest:
      description: It represents the request body of the deregistration request sent by UDM to HSS and contains the IMSI of the UE, the deregistration reason, etc.
      type: object
      required:
        - imsi
        - deregReason
      properties:
        imsi:
          type: string
          pattern: '^[0-9]{5,15}$'
        deregReason:
          $ref: '#/components/schemas/DeregistrationReason'
        guami:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Guami'

    ImeiUpdateInfo:
      description: It represents the request body of the IMEI update request sent by UDM to HSS, and contains the IMSI of the UE and the new IMEI(SV)
      type: object
      required:
        - imsi
      oneOf:
        - required: [ imei ]
        - required: [ imeisv ]
      properties:
        imsi:
          type: string
          pattern: '^[0-9]{5,15}$'
        imei:
          type: string
          pattern: '^[0-9]{14,15}$'
        imeisv:
          type: string
          pattern: '^[0-9]{16}$'

# SIMPLE TYPES:


# ENUMS:

    DeregistrationReason:
      description: The reason that triggers that the serving node needs to be deregistered by HSS
      anyOf:
        - type: string
          enum:
            - UE_INITIAL_AND_SINGLE_REGISTRATION
            - UE_INITIAL_AND_DUAL_REGISTRATION
            - EPS_TO_5GS_MOBILITY
        - type: string
