openapi: 3.0.0

info:
  version: '1.1.0-alpha.1'
  title: 'SEPP Telescopic FQDN Mapping API'
  description: |
    SEPP Telescopic FQDN Mapping Service.
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

servers:
  - url: '{apiRoot}/nsepp-telescopic/v1'
    variables:
      apiRoot:
        default: https://example.com
        description:  apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

externalDocs:
  description: 3GPP TS 29.573 V17.1.0; 5G System; Public Land Mobile Network (PLMN) Interconnection; Stage 3
  url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.573/

paths:
  /mapping:
    get:
      summary: Maps an FQDN to/from a telescopic FQDN
      operationId: GetTelescopicMapping
      tags:
        - Telescopic Mapping (Document)
      parameters:
        - name: foreign-fqdn
          in: query
          description: FQDN of the NF in the foreign PLMN
          schema:
            $ref: 'TS29510_Nnrf_NFManagement.yaml#/components/schemas/Fqdn'
        - name: telescopic-label
          in: query
          description: Telescopic Label
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TelescopicMapping'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

components:
  schemas:
    TelescopicMapping:
      description: Contains the Telescopic mapping data
      type: object
      properties:
        telescopicLabel:
          type: string
        seppDomain:
          $ref: 'TS29510_Nnrf_NFManagement.yaml#/components/schemas/Fqdn'
        foreignFqdn:
          $ref: 'TS29510_Nnrf_NFManagement.yaml#/components/schemas/Fqdn'
