openapi: 3.0.0
info:
  title: 3gpp-service-parameter
  version: 1.1.0-alpha.1
  description: |
    API for AF service paramter
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 29.522 V17.2.0; 5G System; Network Exposure Function Northbound APIs.
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.522/'
security:
  - {}
  - oAuth2ClientCredentials: []
servers:
  - url: '{apiRoot}/3gpp-service-parameter/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in subclause 5.2.4 of 3GPP TS 29.122.

paths:
  /{afId}/subscriptions:
    parameters:
      - name: afId
        in: path
        description: Identifier of the AF
        required: true
        schema:
          type: string
    get:
      summary: read all of the active subscriptions for the AF
      tags:
        - Service Parameter Subscriptions
      responses:
        '200':
          description: OK. 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceParameterData'
                minItems: 0
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    post:
      summary: Creates a new subscription resource 
      tags:
        - Service Parameter Subscriptions
      requestBody:
        description: Request to create a new subscription resource
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceParameterData'
      responses:
        '201':
          description: Created (Successful creation of subscription)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceParameterData'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource'
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /{afId}/subscriptions/{subscriptionId}:
    parameters:
      - name: afId
        in: path
        description: Identifier of the AF
        required: true
        schema:
          type: string
      - name: subscriptionId
        in: path
        description: Identifier of the subscription resource
        required: true
        schema:
          type: string
    get:
      summary: read an active subscriptions for the SCS/AS and the subscription Id
      tags:
        - Individual Service Parameter Subscription
      responses:
        '200':
          description: OK (Successful get the active subscription)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceParameterData'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    put:
      summary: Updates/replaces an existing subscription resource
      tags:
        - Individual Service Parameter Subscription
      requestBody:
        description: Parameters to update/replace the existing subscription
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceParameterData'
      responses:
        '200':
          description: OK (Successful update of the subscription)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceParameterData'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    patch:
      summary: Updates/replaces an existing subscription resource
      tags:
        - Individual Service Parameter Subscription
      requestBody:
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/ServiceParameterDataPatch'
      responses:
        '200':
          description: OK. The subscription was modified successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceParameterData'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    delete:
      summary: Deletes an already existing subscription
      tags:
        - Individual Service Parameter Subscription
      responses:
        '204':
          description: No Content (Successful deletion of the existing subscription)
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}
  schemas: 
    ServiceParameterData:
      description: Represents an individual Service Parameter subscription resource.
      type: object
      properties:
        afServiceId:
          type: string
          description: Identifies a service on behalf of which the AF is issuing the request.
        appId:
          type: string
          description: Identifies an application.
        dnn:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
        snssai:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
        externalGroupId:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/ExternalGroupId'
        anyUeInd:
          type: boolean
          description: Identifies whether the AF request applies to any UE. This attribute shall set to "true" if applicable for any UE, otherwise, set to "false".
        gpsi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        ueIpv4:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Ipv4Addr'
        ueIpv6:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Ipv6Addr'
        ueMac:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/MacAddr48'
        self:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Link'
        paramOverPc5:
          $ref: '#/components/schemas/ParameterOverPc5'
        paramOverUu:
          $ref: '#/components/schemas/ParameterOverUu'
        paramForProSeDd:
          $ref: '#/components/schemas/ParamForProSeDd'
        paramForProSeDc:
          $ref: '#/components/schemas/ParamForProSeDc'
        paramForProSeU2N:
          $ref: '#/components/schemas/ParamForProSeU2N'
        paramForProSeUsageRep:
          $ref: '#/components/schemas/ParamForProSeUsageRep'
        paramForProSeServPathSel:
          $ref: '#/components/schemas/ParamForProSeServPathSel'
        urspInfluence:
          type: array
          items:
            $ref: '#/components/schemas/UrspRuleRequest'
          minItems: 1
          description: Contains the service parameter used to influence the URSP.
        mtcProviderId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/MtcProviderInformation'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
    ServiceParameterDataPatch:
      description: Represents the parameters to request the modification of a service parameter subscription resource.
      type: object
      properties:
        paramOverPc5:
          $ref: '#/components/schemas/ParameterOverPc5Rm'
        paramOverUu:
          $ref: '#/components/schemas/ParameterOverUuRm'
        paramForProSeDd:
          $ref: '#/components/schemas/ParamForProSeDdRm'
        paramForProSeDc:
          $ref: '#/components/schemas/ParamForProSeDcRm'
        paramForProSeU2N:
          $ref: '#/components/schemas/ParamForProSeU2NRm'
        paramForProSeUsageRep:
          $ref: '#/components/schemas/ParamForProSeUsageRepRm'
        paramForProSeServPathSel:
          $ref: '#/components/schemas/ParamForProSeServPathSelRm'
        urspInfluence:
          type: array
          items:
            $ref: '#/components/schemas/UrspRuleRequest'
          minItems: 1
          description: Contains the service parameter used to influence the URSP.
    ParameterOverPc5:
      description: Represents configuration parameters for V2X communications over PC5 reference point.
      type: string
    ParameterOverPc5Rm:
      description: Represents the same as the ParameterOverPc5 data type but with the nullable:true property.
      type: string
      nullable: true
    ParameterOverUu:
      description: Represents configuration parameters for V2X communications over Uu reference point.
      type: string
    ParameterOverUuRm:
      description: Represents the same as the ParameterOverUu data type but with the nullable:true property.
      type: string
      nullable: true
    ParamForProSeDd:
      description: Represents the service parameters for 5G ProSe direct discovery.
      type: string
    ParamForProSeDdRm:
      description: This data type is defined in the same way as the ParamForProSeDd data type, but with the OpenAPI nullable property set to true.
      type: string
      nullable: true
    ParamForProSeDc:
      description: Represents the service parameters for 5G ProSe direct communications.
      type: string
    ParamForProSeDcRm:
      description: This data type is defined in the same way as the ParamForProSeDc data type, but with the OpenAPI nullable property set to true.
      type: string
      nullable: true
    ParamForProSeU2N:
      description: Represents the service parameters for 5G ProSe UE-to-network relay.
      type: string
    ParamForProSeU2NRm:
      description: This data type is defined in the same way as the ParamForProSeU2N data type, but with the OpenAPI nullable property set to true.
      type: string
      nullable: true
    ParamForProSeUsageRep:
      description: Represents the service parameters for 5G ProSe usage reporting configuration and rules.
      type: string
    ParamForProSeUsageRepRm:
      description: This data type is defined in the same way as the ParamForProSeUsageRep data type, but with the OpenAPI nullable property set to true.
      type: string
      nullable: true
    ParamForProSeServPathSel:
      description: Represents the service parameters for 5G ProSe service path selection.
      type: string
    ParamForProSeServPathSelRm:
      description: This data type is defined in the same way as the ParamForProSeServPathSel data type, but with the OpenAPI nullable property set to true.
      type: string
      nullable: true
    UrspRuleRequest:
      description: Contains parameters that can be used to influence the URSP.
      type: object
      properties:
        trafficDesc:
          $ref: 'TS29122_ResourceManagementOfBdt.yaml#/components/schemas/TrafficDescriptor'
        routeSelParamSets:
          type: array
          items:
            $ref: '#/components/schemas/RouteSelectionParameterSet'
          minItems: 1
          description: Sets of parameters that may be used to influence the Route Selection Descriptors of the URSP.
    RouteSelectionParameterSet:
      description: Contains parameters that can be used to influence the Route Selection Descriptors of the URSP.
      type: object
      properties:
        dnn:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
        snssai:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
        precedence:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uinteger'
        spatialValidity:
          type: array
          items:
            type: string
          minItems: 1
          description: Indicates where the route selection parameters apply. It may correspond to a geographical area, for example using a geographic zone identifier that is known to the AF and is configured by the operator to correspond to a list of Cell Ids or TAIs.
