openapi: 3.0.0
info:
  version: 1.2.0-alpha.1
  title: Nausf_UPUProtection Service
  description: |
    AUSF UPU Protection Service
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.509 V17.2.0; 5G System; Authentication Server Services
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.509'

servers:
  - url: '{apiRoot}/nausf-upuprotection/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501.

security:
  - {}
  - oAuth2ClientCredentials:
      - nausf-upuprotection

paths:
  /{supi}/ue-upu:
    post:
      parameters:
        - name: supi
          in: path
          description: Identifier of the UE
          required: true
          schema:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Supi'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpuInfo'
        required: true
      responses:
        '200':
          description: UpuSecurityInfo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpuSecurityInfo'

        '503':
          description: Service Unavailable
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '307':
          description: temporary redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '308':
          description: permanent redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nausf-upuprotection: Access to the Nausf_UPUProtection API

  schemas:

# COMPLEX TYPES:

    UpuInfo:
      description: Contains the UE parameters update Information.
      type: object
      properties:
        upuDataList:
          type: array
          items:
            $ref: '#/components/schemas/UpuData'
          minItems: 1
        upuAckInd:
          $ref: '#/components/schemas/UpuAckInd'
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - upuDataList
        - upuAckInd
    UpuSecurityInfo:
      description: Contains the material generated for securing of UPU. It contains at least the UPU-MAC-IAUSF and CounterUPU.
      type: object
      properties:
        upuMacIausf:
          $ref: '#/components/schemas/UpuMac'
        counterUpu:
          $ref: '#/components/schemas/CounterUpu'
        upuXmacIue:
          $ref: '#/components/schemas/UpuMac'
      required:
        - upuMacIausf
        - counterUpu
    UpuData:
      description: Contains UE parameters update data set (e.g., the updated Routing ID Data or the Default configured NSSAI).
      type: object
      properties:
        secPacket:
          $ref: 'TS29509_Nausf_SoRProtection.yaml#/components/schemas/SecuredPacket'
        defaultConfNssai:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
          minItems: 1
        routingId:
          $ref: 'TS29544_Nspaf_SecuredPacket.yaml#/components/schemas/RoutingId'
      oneOf:
        - required: [secPacket]
        - required: [defaultConfNssai]

# SIMPLE TYPES:

    UpuMac:
      description: MAC value for protecting UPU procedure (UPU-MAC-IAUSF and UPU-MAC-IUE).
      type: string
      pattern: '^[A-Fa-f0-9]{32}$'
    CounterUpu:
      description: CounterUPU.
      type: string
      pattern: '^[A-Fa-f0-9]{4}$'
    UpuAckInd:
      description: Contains the indication of whether the acknowledgement from UE is needed.
      type: boolean
