# Server
server:
  port: 9091

# Client
senf:
  rest:
    baseurl: https://3gppserver.unknown/v1

qod:
  availability:
    enabled: true
    url: http://localhost:8083/

# Health
management:
  server:
    port: 9092
  health:
    probes:
      enabled: true
  info:
    enabled: true
