# Server
server:
  port: 9091

# Client
senf:
  rest:
    baseurl: https://3gppserver.unknown/v1

qod:
  availability:
    enabled: true
    url: https://dev-availability.caas-t03.telekom.de

# Health
management:
  server:
    port: 9092
  health:
    probes:
      enabled: true
  info:
    enabled: true
